/**
 * DSON Portfolio Core Script
 * Features: CMS Data Integration, Bento Grid Logic, Dynamic Modals, and Showcase Filter
 */

// --- Global Variables ---
let modalData = {};
let currentFilter = 'all';
let currentLimit = 6; 

// Initialize components when DOM is fully loaded
document.addEventListener('DOMContentLoaded', () => {
    // Only run if we are on the portfolio page
    if (document.getElementById('portfolio-grid')) {
        loadCMSData();
    }
});

/**
 * CMS Connection Logic
 * Fetches JSON data generated by Decap CMS. 
 * If no data is found, it leaves the grid blank.
 */
async function loadCMSData() {
    const grid = document.getElementById('portfolio-grid');
    try {
        const response = await fetch('data/portfolio.json');
        if (!response.ok) throw new Error('CMS JSON data not found');
        
        const data = await response.json();
        
        if (data && data.works && data.works.length > 0) {
            console.log("CMS Service: Connected & Real Data Loaded 🚀");
            renderDynamicGrid(data.works);
        } else {
            // 如果 JSON 里没有数据，保持空白
            grid.innerHTML = '';
        }
    } catch (err) {
        // 如果找不到 JSON 文件（还没从后台发布），保持空白，不显示假数据
        console.warn("CMS data missing or offline. Leaving grid blank.", err);
        grid.innerHTML = ''; 
    }
}

/**
 * Converts CMS JSON array into HTML Grid and populates Modal Data
 * @param {Array} works - Array of project objects from CMS
 */
function renderDynamicGrid(works) {
    const grid = document.getElementById('portfolio-grid');
    grid.innerHTML = ''; // Clear canvas
    modalData = {}; // Reset modal data

    const catLabels = {
        'uiux': 'UI/UX',
        'photo': 'Photo Editing',
        'manipulation': 'Image Manipulation',
        'video': 'Video Editing',
        '3d': '3D Modeling',
        'graphic': 'Graphic Design'
    };

    works.forEach((work, index) => {
        const uniqueKey = 'cms_project_' + index;
        const displayTag = catLabels[work.category] || work.category;

        // Build Modal Data dynamically
        modalData[uniqueKey] = {
            tag: displayTag,
            title: work.title,
            title_zh: work.title_zh, 
            desc: work.description,
            desc_zh: work.description_zh, 
            tools: work.tools,
            year: work.year,
            client: work.client,
            client_zh: work.client_zh,
            thumbnail: work.thumbnail // ✨ 把图片地址加回来啦！
        };

        // Inject HTML Card
        grid.innerHTML += `
            <div class="portfolio-item" data-cat="${work.category}" onclick="openModal('${uniqueKey}')">
              <div class="portfolio-bg">
                <img src="${work.thumbnail}" alt="${work.title}" class="portfolio-img" onerror="this.src='Image/Logo_Colour.png'">
              </div>
              <div class="portfolio-overlay"></div>
              <div class="portfolio-info">
                <span>${displayTag}</span>
                <h3>${work.title}</h3>
              </div>
            </div>
        `;
    });

    updatePortfolioGrid(); // Apply UI logic
}

/**
 * Filters items based on the selected category
 */
function filterPortfolio(category, btnElement) {
    const buttons = document.querySelectorAll('.filter-btn');
    buttons.forEach(btn => btn.classList.remove('active'));
    
    if (btnElement) {
        btnElement.classList.add('active');
    }

    currentFilter = category;
    currentLimit = 6; 
    updatePortfolioGrid();

    // 切换分类时重新触发动画效果
    setTimeout(() => {
        if (typeof applyPortfolioAnimations === 'function') {
            const allCards = document.querySelectorAll('.portfolio-item');
            allCards.forEach(card => card.classList.remove('aos-animate'));
            
            setTimeout(() => {
                applyPortfolioAnimations();
            }, 50);
        }
    }, 50);
}

/**
 * Loads more items by increasing the display limit
 */
function loadMoreItems() {
    currentLimit += 6; 
    updatePortfolioGrid();
}

/**
 * Core function to update grid visibility and Bento layout
 */
function updatePortfolioGrid() {
    const items = document.querySelectorAll('.portfolio-item');
    const loadMoreContainer = document.getElementById('load-more-container');
    let visibleItems = [];

    // 新逻辑：处理过滤条件 (ALL WORK 橱窗模式)
    if (currentFilter === 'all') {
        const seenCategories = new Set();
        
        items.forEach(item => {
            const itemCat = item.getAttribute('data-cat');
            if (!seenCategories.has(itemCat)) {
                seenCategories.add(itemCat);
                visibleItems.push(item);
            } else {
                item.style.display = 'none'; 
                item.classList.remove('bento-large'); 
            }
        });
    } else {
        items.forEach(item => {
            const itemCat = item.getAttribute('data-cat');
            if (itemCat === currentFilter) {
                visibleItems.push(item);
            } else {
                item.style.display = 'none'; 
                item.classList.remove('bento-large'); 
            }
        });
    }

    // Apply limit and dynamic Bento grid layout
    visibleItems.forEach((item, index) => {
        if (index < currentLimit) {
            item.style.display = 'flex'; 
            
            if (index % 4 === 0 || index % 4 === 3) {
                item.classList.add('bento-large');
            } else {
                item.classList.remove('bento-large');
            }
        } else {
            item.style.display = 'none'; 
        }
    });

    if (loadMoreContainer) {
        loadMoreContainer.style.display = (visibleItems.length > currentLimit) ? 'block' : 'none';
    }
}

// --- Modal Logic ---

function openModal(key) {
    const d = modalData[key];
    if (!d) return;
    
    const mc = document.getElementById('modal-content');
    
    mc.style.maxWidth = '1000px';
    mc.style.width = '90%';
    mc.style.maxHeight = '90vh'; 
    mc.style.overflowY = 'auto'; 
    mc.style.padding = '2.5rem';

    mc.innerHTML = `
        <button class="modal-close" onclick="closeModal({target:document.getElementById('modal-overlay')})">
            <i class="bi bi-x-lg"></i>
        </button>
        <div style="display: flex; gap: 3rem; flex-wrap: wrap; align-items: center;">
            
            <div style="flex: 1 1 450px; position: relative; display: flex; justify-content: center; align-items: center; max-height: 65vh;">
                <img src="${d.thumbnail}" alt="${d.title}" 
                     style="width: 100%; height: 100%; max-height: 65vh; object-fit: contain; border-radius: 12px; cursor: zoom-in; filter: drop-shadow(0 10px 20px rgba(0,0,0,0.3)); transition: transform 0.3s ease;" 
                     onclick="openLightbox('${d.thumbnail}')"
                     onmouseover="this.style.transform='scale(1.02)'" 
                     onmouseout="this.style.transform='scale(1)'"
                     title="Click to enlarge">
            </div>
            
            <div style="flex: 1 1 300px; display: flex; flex-direction: column; justify-content: center;">
                
                <div class="modal-tag" style="font-size: 0.72rem; letter-spacing: 0.15em; text-transform: uppercase; color: var(--accent); margin-bottom: 0.75rem;">
                    ${d.tag}
                </div>
                
                <h2 style="font-family: 'Syne', sans-serif; font-size: 2.2rem; font-weight: 700; margin-bottom: 1.2rem; line-height: 1.1;">
                    <span class="lang-en">${d.title}</span>
                    <span class="lang-zh">${d.title_zh || d.title}</span>
                </h2>
                
                <p style="color: var(--text-muted); line-height: 1.8; margin-bottom: 1.5rem; font-size: 0.95rem;">
                    <span class="lang-en">${d.desc}</span>
                    <span class="lang-zh">${d.desc_zh || d.desc}</span>
                </p>
                
                <div class="modal-meta" style="display: flex; gap: 2rem; border-top: 1px solid rgba(255,255,255,0.1); padding-top: 1.5rem; flex-wrap: wrap;">
                    
                    <div>
                        <label style="display: block; font-size: 0.7rem; color: var(--text-muted); margin-bottom: 6px; text-transform: uppercase; letter-spacing: 0.05em;">
                            <span class="lang-en">Tools</span><span class="lang-zh">使用工具</span>
                        </label>
                        <span style="font-family: 'Inter', sans-serif; font-weight: 500;">${d.tools}</span>
                    </div>
                    
                    <div>
                        <label style="display: block; font-size: 0.7rem; color: var(--text-muted); margin-bottom: 6px; text-transform: uppercase; letter-spacing: 0.05em;">
                            <span class="lang-en">Year</span><span class="lang-zh">创作年份</span>
                        </label>
                        <span style="font-family: 'Inter', sans-serif; font-weight: 500;">${d.year}</span>
                    </div>
                    
                    <div>
                        <label style="display: block; font-size: 0.7rem; color: var(--text-muted); margin-bottom: 6px; text-transform: uppercase; letter-spacing: 0.05em;">
                            <span class="lang-en">Client / Type</span><span class="lang-zh">项目类型</span>
                        </label>
                        <span style="font-family: 'Inter', sans-serif; font-weight: 500;">
                            <span class="lang-en">${d.client}</span>
                            <span class="lang-zh">${d.client_zh || d.client}</span>
                        </span>
                    </div>
                    
                </div>
            </div>
        </div>
    `;
    document.getElementById('modal-overlay').classList.add('open');
}

function closeModal(e) {
    const overlay = document.getElementById('modal-overlay');
    if (e.target === overlay) {
        overlay.classList.remove('open');
    }
}

function openLightbox(imgSrc) {
    let lightbox = document.getElementById('lightbox-overlay');
    
    if (!lightbox) {
        lightbox = document.createElement('div');
        lightbox.id = 'lightbox-overlay';
        lightbox.style.cssText = 'position: fixed; top: 0; left: 0; width: 100vw; height: 100vh; background: rgba(10, 10, 10, 0.85); backdrop-filter: blur(8px); z-index: 9999; display: flex; justify-content: center; align-items: center; cursor: zoom-out; opacity: 0; transition: opacity 0.3s ease;';
        
        lightbox.innerHTML = `<img id="lightbox-img" src="" style="max-width: 90vw; max-height: 90vh; border-radius: 8px; box-shadow: 0 20px 50px rgba(0,0,0,0.6); transform: scale(0.95); transition: transform 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);">`;
        
        lightbox.onclick = function() {
            lightbox.style.opacity = '0';
            document.getElementById('lightbox-img').style.transform = 'scale(0.95)';
            setTimeout(() => { lightbox.style.display = 'none'; }, 300);
        };
        
        document.body.appendChild(lightbox);
    }
    
    const img = document.getElementById('lightbox-img');
    img.src = imgSrc;
    
    lightbox.style.display = 'flex';
    
    requestAnimationFrame(() => {
        lightbox.style.opacity = '1';
        img.style.transform = 'scale(1)';
    });
}

document.addEventListener('keydown', e => {
    if (e.key === 'Escape') {
        const lightbox = document.getElementById('lightbox-overlay');
        if (lightbox && lightbox.style.display === 'flex') {
            lightbox.click();
            return;
        }
        
        const overlay = document.getElementById('modal-overlay');
        if (overlay && overlay.classList.contains('open')) {
            overlay.classList.remove('open');
        }
    }
});