/**
 * DSON Portfolio Core Script - ULTIMATE UNABRIDGED VERSION
 * Features: 
 * - Full CMS Integration (Decap/Netlify CMS)
 * - Smart "All Work" Logic (1 Latest per Category)
 * - Specific Category Pagination (Load More System)
 * - Advanced Dynamic Modals (YouTube Embeds, Figma Prototypes, Image Sliders)
 * - Image Lightbox System (Ghost-click Fixed)
 * - Global Language Sync & Persistence (localStorage)
 * - AOS (Animate On Scroll) Orchestration for Dynamic Content
 * - Touch & Mouse Drag Swipe Support for Gallery
 */

// --- Global Variables ---
let modalData = {};           // Stores project details for modals
let allWorksData = [];        // Raw project list from CMS
let currentFilter = 'all';    // Active category filter
let currentLimit = 6;         // Items limit for specific categories
let currentGallery = [];      // Array for active modal's images
let currentGalleryIndex = 0;  // Index for active modal's slider

// --- 1. System Initialization ---
document.addEventListener('DOMContentLoaded', () => {
    const langLinks = document.querySelectorAll('.lang-switcher a');
    
    // ✨ Memory: Load saved language preference
    const savedLang = localStorage.getItem('selectedLang');
    if (savedLang && langLinks.length > 0) {
        langLinks.forEach(link => {
            const isZhBtn = link.innerText.includes('中文');
            if ((savedLang === 'zh' && isZhBtn) || (savedLang === 'en' && !isZhBtn)) {
                link.classList.add('active');
            } else {
                link.classList.remove('active');
            }
        });
    }

    // Sync static text on page immediately
    syncAllLanguage();

    // Kickstart CMS data loading if on portfolio page
    if (document.getElementById('portfolio-grid')) {
        loadCMSData();
    }

    // Language Switcher Global Listener
    langLinks.forEach(link => {
        link.addEventListener('click', (e) => {
            e.preventDefault();
            langLinks.forEach(l => l.classList.remove('active'));
            link.classList.add('active');
            
            const isChinese = link.innerText.includes('中文');
            localStorage.setItem('selectedLang', isChinese ? 'zh' : 'en');
            
            syncAllLanguage();
            
            // If a modal is open, we re-render it to refresh its language
            const overlay = document.getElementById('modal-overlay');
            if (overlay.classList.contains('open')) {
                const activeKey = overlay.getAttribute('data-current-key');
                if (activeKey) openModal(activeKey);
            }
        });
    });
});

// --- 2. Data Engine & Rendering ---

/**
 * Fetch JSON data generated by CMS
 */
async function loadCMSData() {
    const grid = document.getElementById('portfolio-grid');
    try {
        const response = await fetch('data/portfolio.json');
        if (!response.ok) throw new Error('Portfolio JSON not found');
        
        const data = await response.json();
        if (data && data.works && data.works.length > 0) {
            console.log("CMS Data: Loaded successfully 🚀");
            allWorksData = data.works;
            renderPortfolioUI();
        }
    } catch (err) {
        console.warn("CMS Connection failed. Using placeholder or empty grid.", err);
        if(grid) grid.innerHTML = '';
    }
}

/**
 * Core Render Logic: Orchestrates Grid & Load More Button
 */
function renderPortfolioUI() {
    const grid = document.getElementById('portfolio-grid');
    const loadMoreContainer = document.getElementById('load-more-container');
    if (!grid) return;

    grid.innerHTML = ''; 
    modalData = {}; // Clear previous session data

    const catLabels = {
        'uiux': { en: 'UI/UX', zh: 'UI/UX 设计' },
        'photo': { en: 'Photo Editing', zh: '照片后期' },
        'manipulation': { en: 'Image Manipulation', zh: '图像合成' },
        'video': { en: 'Video Editing', zh: '视频制作' },
        '3d': { en: '3D Modeling', zh: '3D 建模' },
        'graphic': { en: 'Graphic Design', zh: '平面设计' }
    };

    let displayList = [];

    if (currentFilter === 'all') {
        // ✨ SMART HOME LOGIC: Get exactly the latest 1 project from each of the 6 core categories
        const categories = ['video', 'uiux', 'manipulation', '3d', 'graphic', 'photo']; 
        categories.forEach(cat => {
            const latest = allWorksData.find(w => w.category === cat);
            if (latest) displayList.push(latest);
        });
        if (loadMoreContainer) loadMoreContainer.style.display = 'none';
    } else {
        // ✨ CATEGORY MODE: Filter by selected tag and apply current limit for pagination
        const filtered = allWorksData.filter(w => w.category === currentFilter);
        displayList = filtered.slice(0, currentLimit);
        
        if (loadMoreContainer) {
            loadMoreContainer.style.display = (filtered.length > currentLimit) ? 'block' : 'none';
        }
    }

    // Build Grid Cards with Multilingual Metadata
    displayList.forEach((work, index) => {
        const uniqueKey = 'proj_' + index;
        const labels = catLabels[work.category] || { en: work.category, zh: work.category };

        // Save to global modal storage
        modalData[uniqueKey] = { ...work, labels };

        // Bento Grid Logic (Desktop)
        const bentoClass = (index % 4 === 0 || index % 4 === 3) ? 'bento-large' : '';

        grid.innerHTML += `
            <div class="portfolio-item ${bentoClass}" onclick="openModal('${uniqueKey}')">
              <div class="portfolio-bg">
                <img src="${work.thumbnail}" alt="${work.title}" class="portfolio-img" onerror="this.src='Image/Logo_Colour.png'">
              </div>
              <div class="portfolio-overlay"></div>
              <div class="portfolio-info">
                <span class="lang-en">${labels.en}</span>
                <span class="lang-zh">${labels.zh}</span>
                <h3 class="lang-en">${work.title}</h3>
                <h3 class="lang-zh">${work.title_zh || work.title}</h3>
              </div>
            </div>
        `;
    });

    syncAllLanguage(); 
    applyPortfolioAnimations(); 
}

/**
 * Handles category selection from the filter bar
 */
function filterPortfolio(category, btnElement) {
    const buttons = document.querySelectorAll('.filter-btn');
    buttons.forEach(btn => btn.classList.remove('active'));
    if (btnElement) btnElement.classList.add('active');

    currentFilter = category;
    currentLimit = 6; 
    renderPortfolioUI();
}

/**
 * Loads the next batch of projects in category view
 */
function loadMoreItems() {
    currentLimit += 6; 
    renderPortfolioUI();
}

// --- 3. Animation & Language Systems ---

function applyPortfolioAnimations() {
    const items = document.querySelectorAll('.portfolio-item');
    if (items.length > 0) {
        items.forEach((card, index) => {
            card.removeAttribute('data-aos');
            card.classList.remove('aos-animate');
            void card.offsetWidth; 

            const animationType = (index % 2 === 0) ? 'fade-right' : 'fade-left';
            card.setAttribute('data-aos', animationType);
            card.setAttribute('data-aos-delay', (index % 6) * 50); 
        });

        AOS.init({
            duration: 1000,
            easing: 'ease-out-cubic',
            once: true,
            offset: 0 
        });
        
        AOS.refreshHard(); 
    }
}

function syncAllLanguage() {
    const lang = localStorage.getItem('selectedLang') || 'en';
    const enNodes = document.querySelectorAll('.lang-en');
    const zhNodes = document.querySelectorAll('.lang-zh');

    if (lang === 'zh') {
        enNodes.forEach(el => el.style.setProperty('display', 'none', 'important'));
        zhNodes.forEach(el => el.style.setProperty('display', 'block', 'important'));
    } else {
        enNodes.forEach(el => el.style.setProperty('display', 'block', 'important'));
        zhNodes.forEach(el => el.style.setProperty('display', 'none', 'important'));
    }
}

// --- 4. Modal Engine (Full Features & Fixes) ---

function openModal(key) {
    const d = modalData[key];
    if (!d) return;

    const overlay = document.getElementById('modal-overlay');
    const mc = document.getElementById('modal-content');
    overlay.setAttribute('data-current-key', key); 

    mc.style.maxWidth = '1100px';
    mc.style.width = '92%';
    mc.style.maxHeight = '92vh';
    mc.style.overflowY = 'auto';
    mc.style.padding = '3rem';

    let mediaHTML = '';
    
    if (d.youtube_id) {
        mediaHTML = `
            <div style="width: 100%; display: flex; flex-direction: column; gap: 1rem; height:auto;">
                <iframe width="100%" height="100%" 
                        src="https://www.youtube.com/embed/${d.youtube_id}?rel=0&autoplay=0" 
                        title="DSON Project Video" frameborder="0" 
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
                        allowfullscreen
                        style="border-radius:12px; box-shadow:0 10px 30px rgba(0,0,0,0.5); aspect-ratio: 16/9; background:#000;">
                </iframe>
                <a href="https://www.youtube.com/watch?v=${d.youtube_id}" target="_blank" 
                   style="display:flex; align-items:center; justify-content:center; gap:10px; padding:14px; background:rgba(255,255,255,0.05); border:1px solid rgba(255,255,255,0.1); border-radius:10px; color:#fff; text-decoration:none; font-size:0.85rem; transition:0.3s;">
                    <i class="bi bi-youtube" style="color:#ff0000; font-size:1.3rem;"></i>
                    <span class="lang-en">View on YouTube (Original Quality)</span>
                    <span class="lang-zh">前往 YouTube 观看 (原片画质)</span>
                </a>
            </div>`;
    } else if (d.figma_link) {
        mediaHTML = `
            <div style="width: 100%; height: 68vh; background:rgba(0,0,0,0.2); border-radius:12px; overflow:hidden; box-shadow:0 10px 30px rgba(0,0,0,0.5);">
                <iframe style="width:100%; height:100%; border:1px solid rgba(255,255,255,0.1);" 
                        src="https://www.figma.com/embed?embed_host=share&url=${encodeURIComponent(d.figma_link)}" 
                        allowfullscreen>
                </iframe>
            </div>`;
    } else if (d.gallery && d.gallery.length > 1) {
        currentGallery = d.gallery;
        currentGalleryIndex = 0;
        // HTML 中不再嵌入 onclick，全部由底部的事件监听器接管喵！
        mediaHTML = `
            <div style="position:relative; width:100%; display:flex; flex-direction:column; justify-content:center; align-items:center; height:auto;">
                <div style="position:relative; width:100%; display:flex; justify-content:center; align-items:center; user-select: none;">
                    <button class="gallery-nav-btn" onclick="changeGalleryImage(-1)" style="position:absolute; z-index:10; left:15px; background:rgba(0,0,0,0.6); color:white; border:1px solid rgba(255,255,255,0.2); border-radius:50%; width:45px; height:45px; cursor:pointer; font-size:1.2rem; backdrop-filter:blur(5px);"><i class="bi bi-chevron-left"></i></button>
                    <img id="modal-gallery-img" src="${currentGallery[0]}" 
                         class="portfolio-img" draggable="false"
                         style="cursor:zoom-in; transition:opacity 0.2s ease; user-select:none;">
                    <button class="gallery-nav-btn" onclick="changeGalleryImage(1)" style="position:absolute; z-index:10; right:15px; background:rgba(0,0,0,0.6); color:white; border:1px solid rgba(255,255,255,0.2); border-radius:50%; width:45px; height:45px; cursor:pointer; font-size:1.2rem; backdrop-filter:blur(5px);"><i class="bi bi-chevron-right"></i></button>
                </div>
                <div id="gallery-counter" class="gallery-page-counter">1 / ${currentGallery.length}</div>
            </div>`;
    } else {
        mediaHTML = `
            <img src="${d.thumbnail}" alt="${d.title}" 
                 class="portfolio-img"
                 style="cursor:zoom-in;"
                 onclick="openLightbox('${d.thumbnail}')">`;
    }

    // ✨✨✨ FIX 1: d.title 完全替代 work.title，解决崩溃报错喵！
    mc.innerHTML = `
        <button class="modal-close" onclick="closeModal({target:document.getElementById('modal-overlay')})">
            <i class="bi bi-x-lg"></i>
        </button>
        <div style="display:flex; gap:3.5rem; flex-wrap:wrap; align-items:flex-start;">
            <div style="flex:1 1 500px; position:relative; display:flex; justify-content:center; align-items:center; height:auto;">
                ${mediaHTML}
            </div>
            <div style="flex:1 1 350px; display:flex; flex-direction:column; justify-content:center;">
                <div class="project-tag-container" style="font-size:0.75rem; letter-spacing:0.2em; text-transform:uppercase; color:var(--accent); margin-bottom:1rem;">
                    <span class="lang-en">${d.labels.en}</span>
                    <span class="lang-zh">${d.labels.zh}</span>
                </div>
                <h2 class="project-title-h2 lang-en" style="font-family:'Syne'; font-size:2.5rem; font-weight:800; margin-bottom:1.5rem; line-height:1.1;">${d.title}</h2>
                <h2 class="project-title-h2 lang-zh" style="font-family:'Syne'; font-size:2.5rem; font-weight:800; margin-bottom:1.5rem; line-height:1.1;">${d.title_zh || d.title}</h2>
                
                <p class="project-desc-p" style="color:var(--text-muted); line-height:1.9; margin-bottom:2rem; font-size:1rem;">
                    <span class="lang-en">${d.description || d.desc}</span>
                    <span class="lang-zh">${d.description_zh || d.desc_zh || d.desc}</span>
                </p>
                <div class="project-meta-details" style="display:flex; gap:3rem; border-top:1px solid rgba(255,255,255,0.1); padding-top:2rem; flex-wrap:wrap;">
                    <div>
                        <label style="display:block; font-size:0.7rem; color:var(--text-muted); margin-bottom:8px; text-transform:uppercase; letter-spacing:0.1em;">
                            <span class="lang-en">Tools</span><span class="lang-zh">使用工具</span>
                        </label>
                        <span style="font-family:'Inter'; font-weight:600; color:var(--white);">${d.tools}</span>
                    </div>
                    <div>
                        <label style="display:block; font-size:0.7rem; color:var(--text-muted); margin-bottom:8px; text-transform:uppercase; letter-spacing:0.1em;">
                            <span class="lang-en">Year</span><span class="lang-zh">创作年份</span>
                        </label>
                        <span style="font-family:'Inter'; font-weight:600; color:var(--white);">${d.year}</span>
                    </div>
                </div>
            </div>
        </div>
    `;

    overlay.classList.add('open');
    syncAllLanguage(); 

    // ✨✨✨ FIX 2: 精准识别“点击”与“滑动”，根治弹窗重叠 Bug喵！ ✨✨✨
    if (d.gallery && d.gallery.length > 1) {
        const galleryImg = document.getElementById('modal-gallery-img');
        if (galleryImg) {
            let startX = 0;
            let endX = 0;

            // Mobile Touch Events
            galleryImg.addEventListener('touchstart', e => {
                startX = e.changedTouches[0].screenX;
            }, {passive: true});

            galleryImg.addEventListener('touchend', e => {
                endX = e.changedTouches[0].screenX;
                handleSwipeAction();
            });

            // Desktop Mouse Events
            galleryImg.addEventListener('mousedown', e => {
                startX = e.clientX;
                e.preventDefault(); // 阻止浏览器原生的图片拖拽黑影喵
            });

            galleryImg.addEventListener('mouseup', e => {
                endX = e.clientX;
                handleSwipeAction();
            });

            // 划动判定核心逻辑喵
            function handleSwipeAction() {
                if (startX - endX > 40) {
                    changeGalleryImage(1);  // 向左滑 -> 下一张
                } else if (endX - startX > 40) {
                    changeGalleryImage(-1); // 向右滑 -> 上一张
                }
            }

            // 本地原生点击判定，绝不和触控冲突产生Ghost Click喵
            galleryImg.addEventListener('click', e => {
                // 如果刚刚发生了长距离滑动，则拒绝触发“点击放大”喵！
                if (Math.abs(startX - endX) > 10) {
                    return;
                }
                openLightbox(currentGallery[currentGalleryIndex]);
            });
        }
    }
}

/**
 * Gallery Navigation Logic
 */
window.changeGalleryImage = function(direction) {
    if (currentGallery.length === 0) return;
    currentGalleryIndex = (currentGalleryIndex + direction + currentGallery.length) % currentGallery.length;

    const imgEl = document.getElementById('modal-gallery-img');
    const counterEl = document.getElementById('gallery-counter');

    if (imgEl && counterEl) {
        imgEl.style.opacity = '0';
        setTimeout(() => {
            imgEl.src = currentGallery[currentGalleryIndex];
            imgEl.style.opacity = '1';
            counterEl.innerText = `${currentGalleryIndex + 1} / ${currentGallery.length}`;
        }, 200); 
    }
};

/**
 * Modal Disposal Logic
 */
function closeModal(e) {
    const overlay = document.getElementById('modal-overlay');
    if (e.target === overlay || e.target.closest('.modal-close')) {
        overlay.classList.remove('open');
        setTimeout(() => {
            const mc = document.getElementById('modal-content');
            if (mc) mc.innerHTML = '';
        }, 300);
    }
}

// --- 5. Utility & Event Logic ---

/**
 * Fullscreen Image Lightbox Node (性能优化极致丝滑版 ✨)
 */
function openLightbox(imgSrc) {
    let lightbox = document.getElementById('lightbox-overlay');
    if (!lightbox) {
        lightbox = document.createElement('div');
        lightbox.id = 'lightbox-overlay';
        
        // ✨ 优化1：移除极其消耗手机性能的 backdrop-filter，改用 98% 纯黑背景，并开启 opacity 硬件加速
        lightbox.style.cssText = 'position:fixed; top:0; left:0; width:100vw; height:100vh; background:rgba(8,10,15,0.98); z-index:10000; display:flex; justify-content:center; align-items:center; cursor:zoom-out; opacity:0; transition:opacity 0.3s ease; display:none; will-change: opacity;';
        
        // ✨ 优化2：减小阴影渲染压力，开启 transform 硬件加速，确保动画 60fps 丝滑
        lightbox.innerHTML = `<img id="lightbox-img" src="" style="max-width:92vw; max-height:92vh; border-radius:6px; box-shadow:0 10px 25px rgba(0,0,0,0.5); transform:scale(0.95); transition:transform 0.3s cubic-bezier(0.165, 0.84, 0.44, 1); will-change: transform; object-fit: contain;">`;
        
        document.body.appendChild(lightbox);
        
        // 关闭逻辑
        lightbox.onclick = () => {
            lightbox.style.opacity = '0';
            document.getElementById('lightbox-img').style.transform = 'scale(0.95)';
            setTimeout(() => { lightbox.style.display = 'none'; }, 300);
        };
    }
    
    const img = document.getElementById('lightbox-img');
    img.src = imgSrc;
    lightbox.style.display = 'flex';
    
    // ✨ 优化3：使用底层强制回流 (Reflow) 替代玄学定时器，确保动画瞬间顺滑触发
    void lightbox.offsetWidth;
    
    lightbox.style.opacity = '1';
    img.style.transform = 'scale(1)';
}

// Keyboard Navigation
document.addEventListener('keydown', e => {
    // Escape: Close Lightbox or Modal
    if (e.key === 'Escape') {
        const lb = document.getElementById('lightbox-overlay');
        if (lb && lb.style.display === 'flex') return lb.click();
        const mo = document.getElementById('modal-overlay');
        if (mo && mo.classList.contains('open')) closeModal({ target: mo });
    }
    // Arrows: Control Modal Gallery
    if (document.getElementById('modal-gallery-img')) {
        if (e.key === 'ArrowRight') changeGalleryImage(1);
        if (e.key === 'ArrowLeft') changeGalleryImage(-1);
    }
});

// Scroll Events: Back to Top Trigger
document.addEventListener('scroll', () => {
    const btn = document.getElementById('backToTopBtn');
    if (btn) (window.scrollY > 500) ? btn.classList.add('show') : btn.classList.remove('show');
});

window.scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
}